apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixmycar-backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: fixmycar-backend }
  template:
    metadata:
      labels: { app: fixmycar-backend }
    spec:
      serviceAccountName: fixmycar
      containers:
        - name: fixmycar-backend
          image: us-central1-docker.pkg.dev/test1-449514/fixmycar/backend-vertex-ai-search:latest
          imagePullPolicy: Always
          ports: [{ containerPort: 8080 }]
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "test1-449514"
            - name: GOOGLE_CLOUD_LOCATION
              value: "global"
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "true"
            - name: VERTEX_AI_DATASTORE_ID
              value: "confluence-crawler_1754919097875"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
